Id: calibre.calibre
Version: 4.22.0
Name: calibre
Publisher: calibre
License: GNU General Public License v3.0
LicenseUrl: https://github.com/kovidgoyal/calibre/blob/master/LICENSE
AppMoniker: calibre
Tags: ebook, calibre, kobo, kindle, epub, mobi
Description: calibre is a powerful and easy to use e-book manager.
Homepage: https://calibre-ebook.com/
Installers:
  - Arch: x64
    Url: https://download.calibre-ebook.com/4.22.0/calibre-64bit-4.22.0.msi
    Sha256: 0AF41D8DA62659A56012C58B189F8D350E7A10993BC0FCCAF28C13FE03DC2037
    InstallerType: msi

